name: Benchmarks
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.5'
      - name: Install Dependencies
        run: julia --project -e 'using Pkg; Pkg.instantiate();'
      - name: Benchmark Package
        run: julia --project test/benchmarking.jl
